include:
- project: gardenlinux/gardenlinux-package-build
  file:
  - pipeline/pipeline.yml

variables:
  # Define the source of this package
  SOURCE_NAME: 'onmetal-image'
  ORIG_TAR: 'onmetal-image_0.0~git20220927.d73b45a.orig.tar.xz'
